//! Code generation engine — applies an UpgradeProtocol to produce source files.

use std::path::Path;

use crate::protocol::{ProtocolAction, TriadOp, UpgradeProtocol};

use super::scaffold::{generate_rust_function, generate_ts_function};
use super::types::{GeneratedFile, GenerationResult, GeneratorOptions};

/// Apply an upgrade protocol to generate/modify source files.
pub fn apply_protocol(
    project_root: &Path,
    protocol: &UpgradeProtocol,
    options: &GeneratorOptions,
) -> Result<GenerationResult, anyhow::Error> {
    let mut files: Vec<GeneratedFile> = Vec::new();
    let mut reuse_count = 0usize;
    let mut modify_count = 0usize;
    let mut create_count = 0usize;

    for action in &protocol.actions {
        match action.op {
            TriadOp::Reuse => {
                reuse_count += 1;
            }
            TriadOp::Modify => {
                modify_count += 1;
                if let Some(file) = generate_modify_code(action, options) {
                    files.push(file);
                }
            }
            TriadOp::CreateChild => {
                create_count += 1;
                if let Some(file) = generate_create_child_code(action, options) {
                    files.push(file);
                }
            }
        }
    }

    if options.write_files {
        for file in &files {
            let full_path = if let Some(ref output_dir) = options.output_dir {
                output_dir.join(&file.path)
            } else {
                project_root.join(&file.path)
            };
            if let Some(parent) = full_path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(&full_path, &file.content)?;
        }
    }

    Ok(GenerationResult {
        project_root: project_root.to_string_lossy().to_string(),
        protocol_version: protocol.protocol_version.clone(),
        files,
        reuse_count,
        modify_count,
        create_count,
    })
}

fn generate_modify_code(
    action: &ProtocolAction,
    _options: &GeneratorOptions,
) -> Option<GeneratedFile> {
    let node_id = action.node_id.as_deref()?;
    let fission = action.fission.as_ref()?;

    let code = if fission.problem.contains("typescript") || node_id.ends_with(".ts") {
        generate_ts_function(node_id, fission)
    } else {
        generate_rust_function(node_id, fission)
    };

    Some(GeneratedFile {
        path: format!("src/{}.rs", node_id.replace('.', "/")),
        content: format!(
            "// Modified by TriadMind protocol action '{}'\n{}",
            action.reason.as_deref().unwrap_or("modify"),
            code
        ),
        is_new: false,
        source_action: action.reason.clone().unwrap_or_else(|| "modify".into()),
    })
}

fn generate_create_child_code(
    action: &ProtocolAction,
    _options: &GeneratorOptions,
) -> Option<GeneratedFile> {
    let node = action.node.as_ref()?;
    let fission = node.fission.as_ref()?;

    let code = if node
        .source_path
        .as_deref()
        .map(|p| p.ends_with(".ts") || p.ends_with(".tsx"))
        .unwrap_or(false)
    {
        generate_ts_function(&node.node_id, fission)
    } else {
        generate_rust_function(&node.node_id, fission)
    };

    Some(GeneratedFile {
        path: format!("src/{}.rs", node.node_id.replace('.', "/")),
        content: format!(
            "// Generated by TriadMind protocol action '{}'\n{}",
            action.reason.as_deref().unwrap_or("create_child"),
            code
        ),
        is_new: true,
        source_action: action
            .reason
            .clone()
            .unwrap_or_else(|| "create_child".into()),
    })
}
