//! # Dream — Background architecture health analysis ("Dream Engine")
//!
//! Ported from triadmind-core/dream.ts
//!
//! Runs asynchronously in the background to detect architecture rot:
//! - Abstraction deficit hotspots (too many concrete methods)
//! - High fan-out nodes (too many downstream dependencies)
//! - Ghost nodes (missing implementations / unverified dependencies)
//! - Execute-like ratio violations
//!
//! Generates `DreamProposal` suggestions that the user can accept or reject.
//! Rejected proposals feed back into the system as architecture constraints.
//!
//! @LeftBranch: run_dream_analysis, generate_proposals
//! @RightBranch: DreamReport, DreamFinding, DreamProposal, DreamState

// HashMap unused, removed
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::protocol::{TriadCategory, UpgradeProtocol};

// ── Dream Diagnostic ─────────────────────────────────────────────────

/// A single diagnostic event from the dream engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DreamDiagnostic {
    /// Severity level.
    pub level: DreamLevel,
    /// Diagnostic code (e.g. "HIGH_FANOUT", "GHOST_RATIO").
    pub code: String,
    /// Component that generated this diagnostic.
    pub component: String,
    /// Human-readable message.
    pub message: String,
    /// Associated source file.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_path: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DreamLevel {
    Info,
    Warning,
    Error,
}

// ── Dream Evidence ───────────────────────────────────────────────────

/// Supporting evidence for a dream finding.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DreamEvidence {
    /// Type of evidence (metric, node, diagnostic, runtime).
    #[serde(rename = "type")]
    pub evidence_type: String,
    /// Evidence key.
    pub key: String,
    /// Evidence value (stringified).
    pub value: String,
    /// Associated source path.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_path: Option<String>,
}

// ── Dream Finding ───────────────────────────────────────────────────

/// A single architecture finding detected by the dream engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DreamFinding {
    /// Unique finding id.
    pub id: String,
    /// Type of finding.
    #[serde(rename = "type")]
    pub finding_type: DreamFindingType,
    /// Severity.
    pub severity: DreamSeverity,
    /// Short title.
    pub title: String,
    /// Detailed description.
    pub description: String,
    /// Related metric name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metric: Option<String>,
    /// Current metric value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub current_value: Option<serde_json::Value>,
    /// Target threshold.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target_value: Option<serde_json::Value>,
    /// Detection confidence [0.0, 1.0].
    pub confidence: f64,
    /// Supporting evidence.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub evidence: Vec<DreamEvidence>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DreamFindingType {
    Metric,
    Topology,
    Runtime,
    Governance,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DreamSeverity {
    Info,
    Warning,
    Error,
}

// ── Dream Proposal ──────────────────────────────────────────────────

/// A refactoring proposal generated by the dream engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DreamProposal {
    /// Unique proposal id.
    pub id: String,
    /// Short title.
    pub title: String,
    /// Priority.
    pub priority: DreamPriority,
    /// Detection confidence [0.0, 1.0].
    pub confidence: f64,
    /// Architecture category.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<TriadCategory>,
    /// Source file where the issue was found.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_path: Option<String>,
    /// What this proposal aims to achieve.
    pub objective: String,
    /// Expected outcome if applied.
    #[serde(rename = "expectedOutcome")]
    pub expected_outcome: String,
    /// Concrete action steps.
    pub actions: Vec<String>,
    /// Linked finding ids.
    #[serde(
        rename = "linkedFindings",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub linked_findings: Vec<String>,
    /// Supporting evidence.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub evidence: Vec<DreamEvidence>,
    /// Optional upgrade protocol draft for this proposal.
    #[serde(
        rename = "protocolDraft",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub protocol_draft: Option<UpgradeProtocol>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DreamPriority {
    Low,
    Medium,
    High,
}

// ── Dream State ─────────────────────────────────────────────────────

/// Persistent state of the dream engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DreamState {
    #[serde(rename = "schemaVersion")]
    pub schema_version: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "lastRunAt", default)]
    pub last_run_at: Option<String>,
    #[serde(default)]
    pub last_mode: Option<DreamMode>,
    #[serde(default)]
    pub runs: u64,
    #[serde(rename = "lastFindingCount", default)]
    pub last_finding_count: usize,
    #[serde(rename = "lastProposalCount", default)]
    pub last_proposal_count: usize,
}

impl Default for DreamState {
    fn default() -> Self {
        Self {
            schema_version: "1.0".into(),
            updated_at: String::new(),
            last_run_at: None,
            last_mode: None,
            runs: 0,
            last_finding_count: 0,
            last_proposal_count: 0,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DreamMode {
    Manual,
    Idle,
}

// ── Dream Report ────────────────────────────────────────────────────

/// Complete dream analysis report.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DreamReport {
    #[serde(rename = "schemaVersion")]
    pub schema_version: String,
    /// Project name / root.
    pub project: String,
    /// ISO 8601 generation timestamp.
    #[serde(rename = "generatedAt")]
    pub generated_at: String,
    /// Analysis mode (manual or idle).
    pub mode: DreamMode,
    /// Whether the run was skipped.
    pub skipped: bool,
    /// Reason for skipping, if skipped.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub skip_reason: Option<String>,
    /// Configuration snapshot.
    pub config: DreamConfig,
    /// Metrics summary.
    pub metrics: DreamMetricsSnapshot,
    /// Detected findings.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub findings: Vec<DreamFinding>,
    /// Generated proposals.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub proposals: Vec<DreamProposal>,
    /// Diagnostic events.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub diagnostics: Vec<DreamDiagnostic>,
    /// Human-readable summary lines.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub summary: Vec<String>,
}

/// Dream engine configuration snapshot.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DreamConfig {
    pub enabled: bool,
    #[serde(rename = "idleOnly")]
    pub idle_only: bool,
    #[serde(rename = "minHoursBetweenRuns")]
    pub min_hours_between_runs: f64,
    #[serde(rename = "minConfidence")]
    pub min_confidence: f64,
    #[serde(rename = "maxProposals")]
    pub max_proposals: usize,
}

impl Default for DreamConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            idle_only: true,
            min_hours_between_runs: 1.0,
            min_confidence: 0.6,
            max_proposals: 5,
        }
    }
}

/// Metrics snapshot included in the dream report.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DreamMetricsSnapshot {
    #[serde(rename = "triadNodes")]
    pub triad_nodes: usize,
    #[serde(rename = "executeLikeRatio")]
    pub execute_like_ratio: f64,
    #[serde(rename = "ghostRatio")]
    pub ghost_ratio: f64,
    #[serde(rename = "emptyVertices")]
    pub empty_vertices: usize,
}

// ── Run Options ─────────────────────────────────────────────────────

/// Options for running the dream engine.
#[derive(Debug, Clone)]
pub struct DreamRunOptions {
    /// Analysis mode.
    pub mode: DreamMode,
    /// Force run even if not enough time has elapsed.
    pub force: bool,
    /// Maximum number of proposals to generate.
    pub max_proposals: usize,
    /// Minimum confidence threshold for findings.
    pub min_confidence: f64,
}

impl Default for DreamRunOptions {
    fn default() -> Self {
        Self {
            mode: DreamMode::Manual,
            force: false,
            max_proposals: 5,
            min_confidence: 0.6,
        }
    }
}

// ── Constants ───────────────────────────────────────────────────────

/// Prefix for ghost demand entries in node dependencies.
const GHOST_DEMAND_PREFIX: &str = "[Ghost:";

/// Fan-out threshold for high-dependency alerts.
const FANOUT_ALERT_THRESHOLD: usize = 6;

// ── Run Entry Point ─────────────────────────────────────────────────

/// Run the dream engine analysis.
///
/// Loads the triad-map.json, computes topology metrics, detects architecture
/// issues (execute-like ratio, ghost ratio, empty vertices, high fan-out),
/// and generates refactoring proposals.
pub fn run_dream_analysis(
    project_root: &Path,
    map_file: &Path,
    options: &DreamRunOptions,
) -> Result<DreamReport, anyhow::Error> {
    let project = project_root
        .file_name()
        .unwrap_or(project_root.as_os_str())
        .to_string_lossy()
        .to_string();

    let now = crate::sync::chrono_now();

    // ── Load triad-map ────────────────────────────────────────────
    let nodes: Vec<crate::protocol::TriadNodeDefinition> = if map_file.exists() {
        let content = std::fs::read_to_string(map_file)?;
        let trimmed = content.trim().trim_start_matches('\u{FEFF}');
        serde_json::from_str(trimmed).unwrap_or_default()
    } else {
        Vec::new()
    };

    if nodes.is_empty() {
        return Ok(DreamReport {
            schema_version: "1.0".into(),
            project,
            generated_at: now,
            mode: options.mode,
            skipped: true,
            skip_reason: Some("No triad-map.json found or map is empty".into()),
            config: DreamConfig::default(),
            metrics: DreamMetricsSnapshot {
                triad_nodes: 0,
                execute_like_ratio: 0.0,
                ghost_ratio: 0.0,
                empty_vertices: 0,
            },
            findings: Vec::new(),
            proposals: Vec::new(),
            diagnostics: Vec::new(),
            summary: vec!["No topology data to analyze.".into()],
        });
    }

    // ── Compute metrics ───────────────────────────────────────────
    let metrics = crate::verify::compute_verify_metrics(&nodes);

    // ── Detect findings ───────────────────────────────────────────
    let mut findings: Vec<DreamFinding> = Vec::new();
    let mut finding_id = 0u32;

    // Check execute-like ratio
    if metrics.execute_like_ratio > 0.1 {
        finding_id += 1;
        findings.push(DreamFinding {
            id: format!("F{:03}", finding_id),
            finding_type: DreamFindingType::Metric,
            severity: if metrics.execute_like_ratio > 0.3 {
                DreamSeverity::Error
            } else {
                DreamSeverity::Warning
            },
            title: "High execute-like ratio".into(),
            description: format!(
                "{} of {} nodes ({:.1}%) have execute-like method names. \
                 Consider renaming to domain-specific verbs or splitting \
                 overly generic handlers.",
                metrics.execute_like_count,
                metrics.triad_nodes,
                metrics.execute_like_ratio * 100.0,
            ),
            metric: Some("execute_like_ratio".into()),
            current_value: Some(serde_json::json!(metrics.execute_like_ratio)),
            target_value: Some(serde_json::json!(0.1)),
            confidence: ratio_confidence(metrics.execute_like_ratio, 0.1),
            evidence: vec![DreamEvidence {
                evidence_type: "metric".into(),
                key: "execute_like_count".into(),
                value: metrics.execute_like_count.to_string(),
                source_path: None,
            }],
        });
    }

    // Check ghost ratio
    if metrics.ghost_ratio > 0.4 {
        finding_id += 1;
        let ghost_count = metrics.ghost_nodes;
        findings.push(DreamFinding {
            id: format!("F{:03}", finding_id),
            finding_type: DreamFindingType::Topology,
            severity: if metrics.ghost_ratio > 0.6 {
                DreamSeverity::Error
            } else {
                DreamSeverity::Warning
            },
            title: "High ghost node ratio".into(),
            description: format!(
                "{} nodes ({:.1}%) have ghost dependencies. \
                 These represent unresolved or unverified external dependencies.",
                ghost_count,
                metrics.ghost_ratio * 100.0,
            ),
            metric: Some("ghost_ratio".into()),
            current_value: Some(serde_json::json!(metrics.ghost_ratio)),
            target_value: Some(serde_json::json!(0.4)),
            confidence: ratio_confidence(metrics.ghost_ratio, 0.4),
            evidence: vec![DreamEvidence {
                evidence_type: "metric".into(),
                key: "ghost_nodes".into(),
                value: ghost_count.to_string(),
                source_path: None,
            }],
        });
    }

    // Check empty vertices
    if metrics.empty_vertices > 0 {
        finding_id += 1;
        findings.push(DreamFinding {
            id: format!("F{:03}", finding_id),
            finding_type: DreamFindingType::Topology,
            severity: if metrics.empty_vertices > 5 {
                DreamSeverity::Warning
            } else {
                DreamSeverity::Info
            },
            title: "Empty vertices detected".into(),
            description: format!(
                "{} nodes have no problem/demand/answer defined. \
                 These nodes lack the TriadMind fission triple and should \
                 be annotated or removed.",
                metrics.empty_vertices,
            ),
            metric: Some("empty_vertices".into()),
            current_value: Some(serde_json::json!(metrics.empty_vertices)),
            target_value: Some(serde_json::json!(0)),
            confidence: 0.8,
            evidence: Vec::new(),
        });
    }

    // Check high fan-out: find nodes referenced as demand by many others
    let fan_out = compute_fan_out(&nodes);
    let high_fanout_nodes: Vec<_> = fan_out
        .iter()
        .filter(|(_, count)| *count >= FANOUT_ALERT_THRESHOLD)
        .collect();

    if !high_fanout_nodes.is_empty() {
        finding_id += 1;
        let worst = high_fanout_nodes.first().unwrap();
        findings.push(DreamFinding {
            id: format!("F{:03}", finding_id),
            finding_type: DreamFindingType::Topology,
            severity: DreamSeverity::Warning,
            title: "High fan-out nodes".into(),
            description: format!(
                "{} nodes have {} or more downstream dependents. \
                 Top offender: '{}' with {} dependents. \
                 Consider introducing an abstraction layer.",
                high_fanout_nodes.len(),
                FANOUT_ALERT_THRESHOLD,
                worst.0,
                worst.1,
            ),
            metric: Some("max_fan_out".into()),
            current_value: Some(serde_json::json!(worst.1)),
            target_value: Some(serde_json::json!(FANOUT_ALERT_THRESHOLD - 1)),
            confidence: 0.75,
            evidence: high_fanout_nodes
                .iter()
                .take(5)
                .map(|(name, count)| DreamEvidence {
                    evidence_type: "node".into(),
                    key: format!("fan_out_{}", name),
                    value: count.to_string(),
                    source_path: None,
                })
                .collect(),
        });
    }

    // ── Generate proposals ────────────────────────────────────────
    let proposals = generate_proposals(&findings, options, &nodes);

    // ── Build summary ─────────────────────────────────────────────
    let mut summary = Vec::new();
    summary.push(format!(
        "Analyzed {} triad nodes: execute-like={:.1}%, ghost={:.1}%, empty={}",
        metrics.triad_nodes,
        metrics.execute_like_ratio * 100.0,
        metrics.ghost_ratio * 100.0,
        metrics.empty_vertices,
    ));
    summary.push(format!(
        "Findings: {} | Proposals: {}",
        findings.len(),
        proposals.len(),
    ));
    if !proposals.is_empty() {
        summary.push(format!(
            "Top proposal: {} (confidence={:.2})",
            proposals[0].title, proposals[0].confidence,
        ));
    }

    Ok(DreamReport {
        schema_version: "1.0".into(),
        project,
        generated_at: now,
        mode: options.mode,
        skipped: false,
        skip_reason: None,
        config: DreamConfig::default(),
        metrics: DreamMetricsSnapshot {
            triad_nodes: metrics.triad_nodes,
            execute_like_ratio: metrics.execute_like_ratio,
            ghost_ratio: metrics.ghost_ratio,
            empty_vertices: metrics.empty_vertices,
        },
        findings,
        proposals,
        diagnostics: Vec::new(),
        summary,
    })
}

// ── Fan-out Computation ─────────────────────────────────────────────

/// Compute how many other nodes reference each node as a demand/dependency.
fn compute_fan_out(nodes: &[crate::protocol::TriadNodeDefinition]) -> Vec<(String, usize)> {
    let mut fan_map: std::collections::HashMap<String, usize> = std::collections::HashMap::new();

    for node in nodes {
        if let Some(ref fission) = node.fission {
            for demand in &fission.demand {
                // Skip ghost demands and generic contracts
                if demand.starts_with(GHOST_DEMAND_PREFIX) {
                    continue;
                }
                *fan_map.entry(demand.clone()).or_insert(0) += 1;
            }
        }
    }

    let mut sorted: Vec<(String, usize)> = fan_map.into_iter().collect();
    sorted.sort_by(|a, b| b.1.cmp(&a.1));
    sorted
}

// ── Proposal Generation ─────────────────────────────────────────────

/// Generate refactoring proposals from detected findings.
fn generate_proposals(
    findings: &[DreamFinding],
    options: &DreamRunOptions,
    nodes: &[crate::protocol::TriadNodeDefinition],
) -> Vec<DreamProposal> {
    let mut proposals = Vec::new();
    let mut prop_id = 0u32;

    for finding in findings {
        if finding.confidence < options.min_confidence {
            continue;
        }

        prop_id += 1;
        let proposal = match finding.metric.as_deref() {
            Some("execute_like_ratio") => make_execute_like_proposal(prop_id, finding, nodes),
            Some("ghost_ratio") => make_ghost_proposal(prop_id, finding, nodes),
            Some("empty_vertices") => make_empty_vertices_proposal(prop_id, finding),
            Some("max_fan_out") => make_fanout_proposal(prop_id, finding, nodes),
            _ => continue,
        };

        proposals.push(proposal);

        if proposals.len() >= options.max_proposals {
            break;
        }
    }

    // Sort by confidence descending
    proposals.sort_by(|a, b| {
        b.confidence
            .partial_cmp(&a.confidence)
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    proposals
}

fn make_execute_like_proposal(
    id: u32,
    finding: &DreamFinding,
    _nodes: &[crate::protocol::TriadNodeDefinition],
) -> DreamProposal {
    DreamProposal {
        id: format!("P{:03}", id),
        title: "Reduce execute-like naming".into(),
        priority: DreamPriority::Medium,
        confidence: finding.confidence,
        category: None,
        source_path: None,
        objective: "Replace generic execute/run/handle method names with domain-specific verbs"
            .into(),
        expected_outcome: "Improved code readability and clearer architecture boundaries".into(),
        actions: vec![
            "Audit all execute/run/handle methods".into(),
            "Rename to domain-specific verbs (e.g., 'processOrder', 'validatePayment')".into(),
            "Split oversized handler classes by responsibility".into(),
        ],
        linked_findings: vec![finding.id.clone()],
        evidence: finding.evidence.clone(),
        protocol_draft: None,
    }
}

fn make_ghost_proposal(
    id: u32,
    finding: &DreamFinding,
    nodes: &[crate::protocol::TriadNodeDefinition],
) -> DreamProposal {
    let ghost_count = nodes
        .iter()
        .filter(|n| {
            n.fission
                .as_ref()
                .map(|f| f.demand.iter().any(|d| d.starts_with(GHOST_DEMAND_PREFIX)))
                .unwrap_or(false)
        })
        .count();

    DreamProposal {
        id: format!("P{:03}", id),
        title: "Resolve ghost dependencies".into(),
        priority: DreamPriority::High,
        confidence: finding.confidence,
        category: None,
        source_path: None,
        objective: format!(
            "Resolve or remove {} ghost dependency references",
            ghost_count
        ),
        expected_outcome: "Clean dependency graph with only verified edges".into(),
        actions: vec![
            "Run 'triadmind sync --force' to rescan source files".into(),
            "Replace [Ghost:xxx] references with actual type names".into(),
            "Remove references to deleted or moved modules".into(),
        ],
        linked_findings: vec![finding.id.clone()],
        evidence: finding.evidence.clone(),
        protocol_draft: None,
    }
}

fn make_empty_vertices_proposal(id: u32, finding: &DreamFinding) -> DreamProposal {
    DreamProposal {
        id: format!("P{:03}", id),
        title: "Annotate empty vertices".into(),
        priority: DreamPriority::Low,
        confidence: finding.confidence,
        category: None,
        source_path: None,
        objective: "Add problem/demand/answer annotations to empty topology nodes".into(),
        expected_outcome: "Complete fission triples for all topology nodes".into(),
        actions: vec![
            "Identify nodes with missing fission definitions".into(),
            "Add @LeftBranch and @RightBranch annotations in source".into(),
            "Re-run triadmind sync to regenerate the map".into(),
        ],
        linked_findings: vec![finding.id.clone()],
        evidence: finding.evidence.clone(),
        protocol_draft: None,
    }
}

fn make_fanout_proposal(
    id: u32,
    finding: &DreamFinding,
    _nodes: &[crate::protocol::TriadNodeDefinition],
) -> DreamProposal {
    DreamProposal {
        id: format!("P{:03}", id),
        title: "Reduce high fan-out".into(),
        priority: DreamPriority::Medium,
        confidence: finding.confidence,
        category: None,
        source_path: None,
        objective: "Introduce abstraction layers to reduce direct dependency fan-out".into(),
        expected_outcome: "Lower coupling and improved maintainability".into(),
        actions: vec![
            "Identify the top fan-out offenders".into(),
            "Introduce a trait or interface to abstract the dependency".into(),
            "Refactor consumers to depend on the abstraction".into(),
        ],
        linked_findings: vec![finding.id.clone()],
        evidence: finding.evidence.clone(),
        protocol_draft: None,
    }
}

// ── Helpers ─────────────────────────────────────────────────────────

fn ratio_confidence(actual: f64, threshold: f64) -> f64 {
    let delta = (actual - threshold).max(0.0);
    let normalized = if threshold <= 0.0 {
        delta
    } else {
        delta / threshold
    };
    (0.6 + normalized * 0.25).min(0.95)
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── Helper ──────────────────────────────────────────────────
    fn make_triad_node(
        id: &str,
        problem: &str,
        demand: &[&str],
        answer: &[&str],
    ) -> crate::protocol::TriadNodeDefinition {
        crate::protocol::TriadNodeDefinition {
            node_id: id.into(),
            category: Some("core".into()),
            source_path: Some("src/main.rs".into()),
            lifecycle: None,
            fission: Some(crate::protocol::TriadFission {
                problem: problem.into(),
                demand: demand.iter().map(|s| s.to_string()).collect(),
                answer: answer.iter().map(|s| s.to_string()).collect(),
            }),
        }
    }

    #[test]
    fn test_dream_report_skipped_when_no_map() {
        let opts = DreamRunOptions::default();
        let result = run_dream_analysis(
            Path::new("/nonexistent"),
            Path::new("/nonexistent/triad-map.json"),
            &opts,
        );
        assert!(result.is_ok());
        let report = result.unwrap();
        assert!(report.skipped);
    }

    #[test]
    fn test_default_config_values() {
        let cfg = DreamConfig::default();
        assert!(cfg.enabled);
        assert!(cfg.idle_only);
        assert_eq!(cfg.min_confidence, 0.6);
        assert_eq!(cfg.max_proposals, 5);
    }

    #[test]
    fn test_ratio_confidence() {
        assert!((ratio_confidence(0.2, 0.1) - 0.85).abs() < 0.01);
        assert!((ratio_confidence(0.05, 0.1) - 0.6).abs() < 0.01);
        assert!((ratio_confidence(0.5, 0.1) - 0.95).abs() < 0.01); // clamped
    }

    #[test]
    fn test_compute_fan_out() {
        let nodes = vec![
            make_triad_node("A.run", "a", &["String", "Config"], &["Result"]),
            make_triad_node("B.run", "b", &["Config"], &["void"]),
            make_triad_node("C.run", "c", &["Config"], &["bool"]),
            make_triad_node("D.run", "d", &["Request"], &["Response"]),
        ];
        let fan = compute_fan_out(&nodes);
        let config_fan = fan.iter().find(|(k, _)| k == "Config").unwrap();
        assert_eq!(config_fan.1, 3);
        let string_fan = fan.iter().find(|(k, _)| k == "String").unwrap();
        assert_eq!(string_fan.1, 1);
    }

    #[test]
    fn test_proposal_generation_from_findings() {
        let findings = vec![DreamFinding {
            id: "F001".into(),
            finding_type: DreamFindingType::Metric,
            severity: DreamSeverity::Warning,
            title: "Test finding".into(),
            description: "Test".into(),
            metric: Some("execute_like_ratio".into()),
            current_value: Some(serde_json::json!(0.3)),
            target_value: Some(serde_json::json!(0.1)),
            confidence: 0.8,
            evidence: Vec::new(),
        }];
        let nodes: Vec<crate::protocol::TriadNodeDefinition> = Vec::new();
        let opts = DreamRunOptions {
            mode: DreamMode::Manual,
            force: false,
            max_proposals: 5,
            min_confidence: 0.5,
        };
        let proposals = generate_proposals(&findings, &opts, &nodes);
        assert_eq!(proposals.len(), 1);
        assert!(proposals[0].title.contains("execute-like"));
        assert_eq!(proposals[0].linked_findings, vec!["F001"]);
    }
}
